lab1 done
v0blaa/IU5-iOS-2022 pull request #1
Opened 2022-02-26 19:17 UTC by v0blaa

## Товарищ, твой PR - твоя гордость!

- [x] Убедись, что все тесты прошли успешно.
- [x] Проверь, что Pull Request таргетоирован в ТВОЙ ФОРКНУТЫЙ main
- [x] Заполни отчет по лабораторной работе в Google форме
- [x] Улыбнись, ведь ты приобрел новые навыки)

## Важно!

После того, как ты заполнишь отчет по лабе, я или Юра поревьюим его, и напишем комментарии к коду, если будут вопросы.

Когда ты увидишь коментарий "Все ОК, мержи", можешь смержить PR.

- [x] Ты увидел "Все ОК, мержи"?

2022-02-27 16:22 UTC, MrOcumare requested changes

2022-02-27 16:22 UTC, MrOcumare commented on LABS/LAB_1/SquareSum.swift
> +        for i in arrayOfNumber{
Лучше придерживаться единого code style)
Просто чтобы было красивше for i in arrayOfNumber {
sum += i * i

2022-02-27 16:22 UTC, MrOcumare commented on LABS/LAB_1/SequenceСreator.swift
> +        guard finalElement >= 1 else {
По идее если на вход подали 1 то должны получить [1]

2022-02-27 16:22 UTC, MrOcumare commented on LABS/LAB_1/SequenceСreator.swift
> +        guard finalElement >= 1 else {
По идее если на вход подали 1 то должны получить [1]

2022-02-27 16:22 UTC, MrOcumare commented on LABS/LAB_1/SequenceСreator.swift
> +        //либо то же самое через if, не знаю, что лучше использовать
все правильно)
Только поправь условие в блоке guard

2022-02-27 16:22 UTC, MrOcumare commented on LABS/LAB_1/NumberToArray.swift
> +        repeat {
Ой)
Это конечно здорово, но лучше перепиши на нормальный while )

2022-02-27 16:22 UTC, MrOcumare commented on LABS/LAB_1/BooleanConverter.swift
> +        else if string == "NO"{
код стайл 
if <> {
} else {
}

2022-02-27 16:22 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +        // можно было обрпботать первое число и в самом цикле, но этот ввариант показался более читаемым
Норм 
Главное что сделала за O(N)

2022-02-27 16:22 UTC, MrOcumare commented on LABS/LAB_0/SwapValues.swift
> +        (employeePayroll.luppaSalary, employeePayroll.puppaSalary) = (employeePayroll.puppaSalary, employeePayroll.luppaSalary)
Good)

2022-02-27 17:07 UTC, v0blaa commented on LABS/LAB_1/SequenceСreator.swift
> +        guard finalElement >= 1 else {
Я написала еще тест и перепроверила. Функция возвращает [1], если получает на вход 1, так что все вроде хорошо в этом месте

2022-02-28 19:51 UTC, MrOcumare commented
Все ОК, мержи

2022-03-05 11:14 UTC, merged