Lab number4
v0blaa/IU5-iOS-2022 pull request #4
Opened 2022-03-27 21:28 UTC by v0blaa

## Товарищ, твой PR - твоя гордость!

- [ ] Убедись, что все тесты прошли успешно.
- [ ] Проверь, что Pull Request таргетоирован в ТВОЙ ФОРКНУТЫЙ main
- [ ] Заполни отчет по лабораторной работе в Google форме
- [ ] Улыбнись, ведь ты приобрел новые навыки)

## Важно!

После того, как ты заполнишь отчет по лабе, я или Юра поревьюим его, и напишем комментарии к коду, если будут вопросы.

Когда ты увидишь коментарий "Все ОК, мержи", можешь смержить PR.

- [ ] Ты увидел "Все ОК, мержи"?

2022-03-29 23:24 UTC, MrOcumare requested changes

2022-03-29 23:24 UTC, MrOcumare commented on LABS/LAB_4/FourthViewController/ControllersViewController.swift
> +        super.viewDidLoad()
у тебя нигде не проставлен view.backgroundColor 
из-за этого у тебя скорее всего немного некрасиво происходит анимация открытия

2022-03-29 23:24 UTC, MrOcumare commented on LABS/LAB_4/FourthViewController/ControllersViewController.swift
> +
Вот так константы лучше не объявлять 
вместо этого используй прям внутри текущего класса 
private enum Constants {
    static let longDistanceBetweenViews: CGFloat = 30
    ...
}
А потом в коде используй нужные тебе значения Constants.longDistanceBetweenViews 
Так как параметры ты задаешь как static то инициализировать экземпляр Constants тебе не придется

2022-03-29 23:24 UTC, MrOcumare commented on LABS/LAB_4/FourthViewController/ControllersViewController.swift
> +        let labelWidth: CGFloat = 100
Опят таки лучше чтобы все константы были в одном месте перед глазами (в enum Constants)

2022-03-29 23:24 UTC, MrOcumare commented on LABS/LAB_4/InitialViewController/InitialViewController.swift
> +    private enum cellsDisplayData: String, CaseIterable {
Смотри у тебя cellsDisplayData - это новый тип данных
А все типы следует писать с большой буквы

2022-03-29 23:24 UTC, MrOcumare commented on LABS/LAB_4/InitialViewController/InitialViewController.swift
> +        case lab4 = "Лабораторная работа №4"
За CaseIterable респект

2022-03-29 23:24 UTC, MrOcumare commented on LABS/LAB_4/SecondViewController/MenuViewController.swift
> +        let buttonsDistance: CGFloat = 30
В константы этих джентельменов

2022-03-29 23:24 UTC, MrOcumare commented on LABS/LAB_4/SecondViewController/MenuViewController.swift
> +        tableButton.frame = CGRect(x: (view.frame.width - buttonWidth * 2 - buttonsDistance) / 2,
Не плохо)

2022-03-29 23:24 UTC, MrOcumare commented on LABS/LAB_4/ThirdViewController/BiologyTableCell.swift
> +        let horisontalDistance: CGFloat = 30
В константы

2022-03-29 23:24 UTC, MrOcumare commented on LABS/LAB_4/ThirdViewController/BiologyTableCell.swift
> +        titleLabel.text = ""
молодец

2022-03-29 23:24 UTC, MrOcumare commented on LABS/LAB_4/ThirdViewController/BiologyViewController.swift
> +    private enum cellsDisplayTitle: String, CaseIterable {
Не забываем что типы с Заглавной буквы

2022-03-29 23:24 UTC, MrOcumare commented on LABS/LAB_4/ThirdViewController/BiologyViewController.swift
> +        return 30
По идее такие значения тоже надо в константы

2022-03-29 23:24 UTC, MrOcumare commented on LABS/LAB_4/ThirdViewController/BiologyViewController.swift
> +        return 100
В константы

2022-03-29 23:24 UTC, MrOcumare commented on LABS/LAB_4/ThirdViewController/BiologyViewController.swift
> +        return 30
В константы

2022-03-29 23:26 UTC, MrOcumare commented
Молодец, так держать!
Поправь коменты (не забывай писать под поправленными коментами Done или Ok, так нам будет легче перепроверять)

2022-03-29 23:27 UTC, MrOcumare requested changes

2022-03-29 23:27 UTC, MrOcumare commented on LABS/LAB_4/FourthViewController/ControllersViewController.swift
> +//  Created by Сергей Адольевич on 24.03.2022.
А это кто?)

2022-03-30 06:02 UTC, v0blaa commented on LABS/LAB_4/FourthViewController/ControllersViewController.swift
> +//  Created by Сергей Адольевич on 24.03.2022.
папин старый ноут, я имя пользователя не меняла)))

2022-03-30 16:38 UTC, MrOcumare commented on LABS/LAB_4/FourthViewController/ControllersViewController.swift
> +//  Created by Сергей Адольевич on 24.03.2022.
Понял)

2022-03-31 13:32 UTC, v0blaa commented on LABS/LAB_4/FourthViewController/ControllersViewController.swift
> +//  Created by Сергей Адольевич on 24.03.2022.
все исправлено😎

2022-03-31 13:33 UTC, v0blaa commented on LABS/LAB_4/FourthViewController/ControllersViewController.swift
> +        super.viewDidLoad()
все исправлено😎

2022-04-03 15:54 UTC, MrOcumare commented
Все хорошо, закрывай)

2022-04-04 14:59 UTC, merged